# Generated by Django 6.0.5 on 2026-06-27 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landsystem', '0003_casedocument'),
    ]

    operations = [
        # Rename our custom app tables (remove landsystem_ prefix)
        migrations.AlterModelTable(name='case', table='cases'),
        migrations.AlterModelTable(name='casedocument', table='case_documents'),
        migrations.AlterModelTable(name='citizen', table='citizens'),
        migrations.AlterModelTable(name='officerprofile', table='officers'),
    ]
