# Generated by Django 6.0.6 on 2026-06-29 11:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsystem', '0004_alter_case_table_alter_casedocument_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='current_level',
            field=models.CharField(choices=[('village', 'Village Officer'), ('ward', 'Ward Officer'), ('district_land_officer', 'District Land Officer'), ('land_housing_tribunal', 'Land and Housing Tribunal'), ('high_court', 'High Court')], default='village', max_length=30),
        ),
        migrations.AddField(
            model_name='case',
            name='level_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='level',
            field=models.CharField(choices=[('village', 'Village Officer'), ('ward', 'Ward Officer'), ('district_land_officer', 'District Land Officer'), ('land_housing_tribunal', 'Land and Housing Tribunal'), ('high_court', 'High Court')], default='village', max_length=30),
        ),
    ]
