# Generated by Django 6.0.6 on 2026-07-02 05:43

from django.db import migrations, models


def rename_land_housing_tribunal_forward(apps, schema_editor):
    """'land_housing_tribunal' was renamed to 'regional' - update existing rows."""
    Case = apps.get_model('landsystem', 'Case')
    OfficerProfile = apps.get_model('landsystem', 'OfficerProfile')
    Case.objects.filter(current_level='land_housing_tribunal').update(current_level='regional')
    OfficerProfile.objects.filter(level='land_housing_tribunal').update(level='regional')


def rename_land_housing_tribunal_backward(apps, schema_editor):
    Case = apps.get_model('landsystem', 'Case')
    OfficerProfile = apps.get_model('landsystem', 'OfficerProfile')
    Case.objects.filter(current_level='regional').update(current_level='land_housing_tribunal')
    OfficerProfile.objects.filter(level='regional').update(level='land_housing_tribunal')


class Migration(migrations.Migration):

    dependencies = [
        ('landsystem', '0005_case_current_level_case_level_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='current_level',
            field=models.CharField(choices=[('village', 'Village Officer'), ('ward', 'Ward Officer'), ('district_land_officer', 'District Land Officer'), ('regional', 'Regional Officer'), ('high_court', 'High Court')], default='village', max_length=30),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='level',
            field=models.CharField(choices=[('village', 'Village Officer'), ('ward', 'Ward Officer'), ('district_land_officer', 'District Land Officer'), ('regional', 'Regional Officer'), ('high_court', 'High Court')], default='village', max_length=30),
        ),
        migrations.RunPython(rename_land_housing_tribunal_forward, rename_land_housing_tribunal_backward),
    ]
