# Generated by Django 6.0.6 on 2026-07-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsystem', '0006_alter_case_current_level_alter_officerprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
