# Generated by Django 6.0.6 on 2026-07-14 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsystem', '0007_officerprofile_jurisdiction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('solved', 'Solved'), ('not_solved', 'Not Solved'), ('not_listened', 'Not Listened To')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='landsystem.case')),
            ],
            options={
                'db_table': 'case_feedback',
            },
        ),
    ]
