# Generated by Django 6.0.6 on 2026-07-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsystem', '0008_casefeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='ward',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
