# Generated by Django 6.0.6 on 2026-07-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsystem', '0009_case_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='current_level',
            field=models.CharField(choices=[('village', 'Village Officer'), ('street', 'Street Officer'), ('ward', 'Ward Officer'), ('district_land_officer', 'District Land Officer'), ('regional', 'Regional Officer'), ('high_court', 'High Court')], default='village', max_length=30),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='level',
            field=models.CharField(choices=[('village', 'Village Officer'), ('street', 'Street Officer'), ('ward', 'Ward Officer'), ('district_land_officer', 'District Land Officer'), ('regional', 'Regional Officer'), ('high_court', 'High Court')], default='village', max_length=30),
        ),
    ]
