# Generated by Django 6.0.6 on 2026-07-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsystem', '0010_alter_case_current_level_alter_officerprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='region',
            field=models.CharField(choices=[('arusha', 'Arusha'), ('dar_es_salaam', 'Dar es Salaam'), ('dodoma', 'Dodoma'), ('geita', 'Geita'), ('iringa', 'Iringa'), ('kagera', 'Kagera'), ('katavi', 'Katavi'), ('kigoma', 'Kigoma'), ('kilimanjaro', 'Kilimanjaro'), ('lindi', 'Lindi'), ('manyara', 'Manyara'), ('mara', 'Mara'), ('mbeya', 'Mbeya'), ('morogoro', 'Morogoro'), ('mtwara', 'Mtwara'), ('mwanza', 'Mwanza'), ('njombe', 'Njombe'), ('pwani', 'Pwani (Coast)'), ('rukwa', 'Rukwa'), ('ruvuma', 'Ruvuma'), ('shinyanga', 'Shinyanga'), ('simiyu', 'Simiyu'), ('singida', 'Singida'), ('songwe', 'Songwe'), ('tabora', 'Tabora'), ('tanga', 'Tanga'), ('kaskazini_unguja', 'Kaskazini Unguja (North Unguja)'), ('kusini_unguja', 'Kusini Unguja (South Unguja)'), ('mjini_magharibi', 'Mjini Magharibi (Urban West)'), ('kaskazini_pemba', 'Kaskazini Pemba (North Pemba)'), ('kusini_pemba', 'Kusini Pemba (South Pemba)')], default='dodoma', max_length=50),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='region',
            field=models.CharField(choices=[('arusha', 'Arusha'), ('dar_es_salaam', 'Dar es Salaam'), ('dodoma', 'Dodoma'), ('geita', 'Geita'), ('iringa', 'Iringa'), ('kagera', 'Kagera'), ('katavi', 'Katavi'), ('kigoma', 'Kigoma'), ('kilimanjaro', 'Kilimanjaro'), ('lindi', 'Lindi'), ('manyara', 'Manyara'), ('mara', 'Mara'), ('mbeya', 'Mbeya'), ('morogoro', 'Morogoro'), ('mtwara', 'Mtwara'), ('mwanza', 'Mwanza'), ('njombe', 'Njombe'), ('pwani', 'Pwani (Coast)'), ('rukwa', 'Rukwa'), ('ruvuma', 'Ruvuma'), ('shinyanga', 'Shinyanga'), ('simiyu', 'Simiyu'), ('singida', 'Singida'), ('songwe', 'Songwe'), ('tabora', 'Tabora'), ('tanga', 'Tanga'), ('kaskazini_unguja', 'Kaskazini Unguja (North Unguja)'), ('kusini_unguja', 'Kusini Unguja (South Unguja)'), ('mjini_magharibi', 'Mjini Magharibi (Urban West)'), ('kaskazini_pemba', 'Kaskazini Pemba (North Pemba)'), ('kusini_pemba', 'Kusini Pemba (South Pemba)')], max_length=50),
        ),
    ]
