# Generated by Django 6.0.6 on 2026-07-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsystem', '0011_officerprofile_district_alter_case_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
