# Generated by Django 6.0.5 on 2026-06-27 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landsystem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='citizen_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='case',
            name='region',
            field=models.CharField(choices=[('arusha', 'Arusha Region'), ('dar_es_salaam', 'Dar es Salaam'), ('dodoma', 'Dodoma Region'), ('iringa', 'Iringa Region'), ('kagera', 'Kagera Region'), ('mbeya', 'Mbeya Region'), ('mwanza', 'Mwanza Region'), ('tanga', 'Tanga Region')], default='dodoma', max_length=50),
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='citizen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_cases', to='landsystem.citizen'),
        ),
        migrations.CreateModel(
            name='OfficerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('arusha', 'Arusha Region'), ('dar_es_salaam', 'Dar es Salaam'), ('dodoma', 'Dodoma Region'), ('iringa', 'Iringa Region'), ('kagera', 'Kagera Region'), ('mbeya', 'Mbeya Region'), ('mwanza', 'Mwanza Region'), ('tanga', 'Tanga Region')], max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='officer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
